-- Fix admin user creation using proper Supabase auth table structure
-- Insert admin user into auth.users with proper fields
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  invited_at,
  confirmation_token,
  confirmation_sent_at,
  recovery_token,
  recovery_sent_at,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_token_current,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  '8d6da7b1-33ba-4449-8ea2-28da23e107ec',
  'authenticated',
  'authenticated',
  'admin@company.com',
  crypt('admin123', gen_salt('bf')),
  now(),
  null,
  '',
  null,
  '',
  null,
  '',
  '',
  null,
  null,
  '{"provider": "email", "providers": ["email"]}',
  '{"sub": "8d6da7b1-33ba-4449-8ea2-28da23e107ec", "email": "admin@company.com"}',
  false,
  now(),
  now(),
  null,
  null,
  '',
  '',
  null,
  '',
  0,
  null,
  '',
  null,
  false,
  null
);

-- Insert corresponding auth.identities record
INSERT INTO auth.identities (
  id,
  user_id,
  identity_data,
  provider,
  provider_id,
  last_sign_in_at,
  created_at,
  updated_at,
  email
) VALUES (
  gen_random_uuid(),
  '8d6da7b1-33ba-4449-8ea2-28da23e107ec',
  jsonb_build_object(
    'sub', '8d6da7b1-33ba-4449-8ea2-28da23e107ec',
    'email', 'admin@company.com',
    'email_verified', true,
    'phone_verified', false
  ),
  'email',
  '8d6da7b1-33ba-4449-8ea2-28da23e107ec',
  null,
  now(),
  now(),
  'admin@company.com'
);