// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdsayzxcvpktelbffcyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkc2F5enhjdnBrdGVsYmZmY3lxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMDA4MTEsImV4cCI6MjA3Mzc3NjgxMX0.uu3EdduvAC3UlCOx4UoQqPIXdxICT-fbayefwdieMQY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});